name: Docker Image Build For SiteRM Agent

on:
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the BASE Docker image
      run: | 
        cd siterm-startup/helpers/base_images/agent/
        docker build . --file Dockerfile --build-arg RELEASE=${{ github.event.inputs.buildtag }} --tag sdnsense/siteagent-base:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push BASE Image with tag and date
      run: docker push sdnsense/siteagent-base:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push BASE Image with tag
      run: |
        docker tag sdnsense/siteagent-base:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) sdnsense/siteagent-base:${{ github.event.inputs.buildtag }}
        docker push sdnsense/siteagent-base:${{ github.event.inputs.buildtag }}

    - name: Build the AGENT Docker image
      run: | 
        cd siterm-startup/agent/container-build-files/
        docker build . --file Dockerfile --build-arg RELEASE=${{ github.event.inputs.buildtag }} --tag sdnsense/site-agent-sense:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push AGENT Image with tag and date
      run: docker push sdnsense/site-agent-sense:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push AGENT Image with tag
      run: |
        docker tag sdnsense/site-agent-sense:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) sdnsense/site-agent-sense:${{ github.event.inputs.buildtag }}
        docker push sdnsense/site-agent-sense:${{ github.event.inputs.buildtag }}
