name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ "master" ]
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup

    - name: Build the Docker image
      run: | 
        cd siterm-startup/agent/container-build-files/
        docker build . --file Dockerfile --build-arg RELEASE=${{ github.event.inputs.buildtag }} . --tag sdnsense/site-agent-sense:${{ github.event.inputs.buildtag }}-$(date +%s) --tag sdnsense/site-agent-sense:${{ github.event.inputs.buildtag }}
