name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup

    - name: Build the Docker image
      run: | 
        cd siterm-startup/agent/container-build-files/
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
