# checkov:skip=CKV_GHA_7 User input is controlled and intended for tag/branch selection
name: Docker Image Build For SiteRM FE

on:
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"
      branch:
        description: "Branch to use of siterm/ansible-collections code?"
        default: "master"
        type: "string"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the BASE Docker image
      run: | 
        cd siterm-startup/helpers/base_images/fe/
        docker build . --file Dockerfile --build-arg ARCH=amd64 --tag sdnsense/sitefe-base:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push BASE Image with tag and date
      run: docker push sdnsense/sitefe-base:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push BASE Image with tag
      run: |
        docker tag sdnsense/sitefe-base:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) sdnsense/sitefe-base:${{ github.event.inputs.buildtag }}
        docker push sdnsense/sitefe-base:${{ github.event.inputs.buildtag }}

    - name: Build the FE Docker image
      run: | 
        cd siterm-startup/fe/container-build-files/
        docker build . --file Dockerfile --build-arg RELEASE=${{ github.event.inputs.buildtag }} --build-arg GITBR=${{ github.event.inputs.branch }} --tag sdnsense/site-rm-sense:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push FE Image with tag and date
      run: docker push sdnsense/site-rm-sense:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push FE Image with tag
      run: |
        docker tag sdnsense/site-rm-sense:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) sdnsense/site-rm-sense:${{ github.event.inputs.buildtag }}
        docker push sdnsense/site-rm-sense:${{ github.event.inputs.buildtag }}
